[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aktiendb"
version = "0.1"
dependencies = [
    "pandas",
    "yfinance",
    "supabase",
    "python-dotenv",
    "schedule",
]

[tool.setuptools]
packages = ["palettify",]
[project.scripts]
palettify = "app.updateDatabase:update"
