name: Update Database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-zen-browser:
    name: Update Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update hashes and test build
        run: |
          nix shell . --command aktiendb-update