name: Update Database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-zen-browser:
    name: Update Database
    runs-on: ubuntu-latest
    environment: updateEnv
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update hashes and test build
        env:
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run:
          nix shell . --command aktiendb-update $SUPABASE_URL $SUPABASE_SERVICE_KEY
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update record"
          file_pattern: "*"